on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:  # Gatilho manual

jobs:
  ci-php-reusable:
    runs-on: ubuntu-latest

    # Usando o workflow reutilizável
    uses: fcabick/central-reusable/.github/workflows/php-reusable.yml@main
    with:
      language: "php"
      environment: "ci"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ci-php-manual:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a file with the API_KEY
        run: |
          echo "PROJ_KEY=fcabick_php-pipelines" > .proj_key
