on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:  # Gatilho manual

jobs:
  ci-php:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a file with the API_KEY
        run: |
          echo "PROJ_KEY=fcabick_php-pipelines" > .proj_key

      - name: Run PHP tests (exemplo de step manual)
        run: |
          # Aqui você pode adicionar outros comandos para rodar os testes, por exemplo
          php -v
