on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
  workflow_dispatch:  # Gatilho manual

jobs:
  ci-php-reusable:
    # Usando o workflow reutilizável
    uses: fcabick/central-reusable/.github/workflows/php-reusable.yml@main
    with:
      language: "php"
      environment: "ci"
      
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
